version: "3.9"

services:
  transaction-server:
    image: ep:latest
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: generator-daemon
    tty: true
    stdin_open: true
    depends_on:
      timescaledb:
        condition: service_healthy
    ports:
      - "5050:5050"
    environment:
      DB_CONNECTION: "Host=timescaledb;Port=5432;Username=postgres;Password=postgres;Database=postgres;Pooling=true;MaxPoolSize=20;"
      LIMIT: 2
      PORT: 5050
    entrypoint: ["dotnet", "./TransactionServer/TransactionServer.dll"]

  generator-daemon:
    image: ep:latest
    entrypoint: ["dotnet", "./GeneratorDaemon/GeneratorDaemon.dll"]
    tty: true
    stdin_open: true
    environment:
      DB_CONNECTION: "Host=timescaledb;Port=5432;Username=postgres;Password=postgres;Database=postgres;Pooling=true;MaxPoolSize=20;"
      LIMIT: 2
      PORT: 5050
    depends_on:
      timescaledb:
        condition: service_healthy

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: ts
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6969:5432"
    volumes:
      - ./api/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      retries: 10
      timeout: 5s
